<a href="https://colab.research.google.com/github/nsanced/poblacion-mundial-2023/blob/main/poblacion_mundial_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabajo previo

In [ ]:
from google.colab import drive
#drive.mount("/content/drive")

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
filename = "/content/drive/MyDrive/Fondo Talento Digital - Es Hoy/Semana 4: Dashboards (PowerBI, Tableau) y Storytelling/Global Population 2023 - Global Population-3.csv"
df = pd.read_csv(filename)
df.head(10)

,#,Country (or dependency),Population\n(2023),Yearly\nChange,Net\nChange,Density\n(P/Km²),Land Area\n(Km²),Migrants\n(net),Fert.\nRate,Med.\nAge,Urban\nPop %,World\nShare
0,1,India,"1,428,627,663",0.81 %,11454490,481,2973190,-486136,2.0,28.0,36 %,17.76 %
1,2,China,"1,425,671,352",-0.02 %,-215985,152,9388211,-310220,1.2,39.0,65 %,17.72 %
2,3,United States,"339,996,563",0.50 %,1706706,37,9147420,999700,1.7,38.0,83 %,4.23 %
3,4,Indonesia,"277,534,122",0.74 %,2032783,153,1811570,-49997,2.1,30.0,59 %,3.45 %
4,5,Pakistan,"240,485,658",1.98 %,4660796,312,770880,-165988,3.3,21.0,35 %,2.99 %
5,6,Nigeria,"223,804,632",2.41 %,5263420,246,910770,-59996,5.1,17.0,54 %,2.78 %
6,7,Brazil,"216,422,446",0.52 %,1108948,26,8358140,6000,1.6,34.0,88 %,2.69 %
7,8,Bangladesh,"172,954,319",1.03 %,1767947,"1,329",130170,-309977,1.9,27.0,41 %,2.15 %
8,9,Russia,"144,444,359",-0.19 %,-268955,9,16376870,-136414,1.5,39.0,75 %,1.80 %
9,10,Mexico,"128,455,567",0.75 %,951442,66,1943950,-50239,1.8,30.0,88 %,1.60 %

# Analizar y limpiar datos

In [ ]:
df.rename(columns={"Country (or dependency)": "Country_(OrDependency)", "Population\n(2023)": "Population_2023", "Yearly\nChange": "Yearly_Change(%)", "Net\nChange": "Net_Change", \
                   "Density\n(P/Km²)": "Density_(P/Km²)", "Land Area\n(Km²)": "LandArea_(Km²)", "Migrants\n(net)": "Migrants_(net)", "Fert.\nRate": "Fert_Rate", \
                   "Med.\nAge": "Med_Age", "Urban\nPop %": "Urban_Pop(%)", "World\nShare": "World_Share(%)"}, inplace=True)
df.drop(["#"], axis=1, inplace=True)
df.head(10)

,Country_(OrDependency),Population_2023,Yearly_Change(%),Net_Change,Density_(P/Km²),LandArea_(Km²),Migrants_(net),Fert_Rate,Med_Age,Urban_Pop(%),World_Share(%)
0,India,"1,428,627,663",0.81 %,11454490,481,2973190,-486136,2.0,28.0,36 %,17.76 %
1,China,"1,425,671,352",-0.02 %,-215985,152,9388211,-310220,1.2,39.0,65 %,17.72 %
2,United States,"339,996,563",0.50 %,1706706,37,9147420,999700,1.7,38.0,83 %,4.23 %
3,Indonesia,"277,534,122",0.74 %,2032783,153,1811570,-49997,2.1,30.0,59 %,3.45 %
4,Pakistan,"240,485,658",1.98 %,4660796,312,770880,-165988,3.3,21.0,35 %,2.99 %
5,Nigeria,"223,804,632",2.41 %,5263420,246,910770,-59996,5.1,17.0,54 %,2.78 %
6,Brazil,"216,422,446",0.52 %,1108948,26,8358140,6000,1.6,34.0,88 %,2.69 %
7,Bangladesh,"172,954,319",1.03 %,1767947,"1,329",130170,-309977,1.9,27.0,41 %,2.15 %
8,Russia,"144,444,359",-0.19 %,-268955,9,16376870,-136414,1.5,39.0,75 %,1.80 %
9,Mexico,"128,455,567",0.75 %,951442,66,1943950,-50239,1.8,30.0,88 %,1.60 %

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country_(OrDependency)  234 non-null    object
 1   Population_2023         234 non-null    object
 2   Yearly_Change(%)        234 non-null    object
 3   Net_Change              234 non-null    int64
 4   Density_(P/Km²)         234 non-null    object
 5   LandArea_(Km²)          234 non-null    int64
 6   Migrants_(net)          234 non-null    int64
 7   Fert_Rate               233 non-null    float64
 8   Med_Age                 233 non-null    float64
 9   Urban_Pop(%)            234 non-null    object
 10  World_Share(%)          234 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 20.2+ KB

In [ ]:
FertNan_filter = df["Fert_Rate"].isna()
AgeNan_filter = df["Med_Age"].isna()
df.loc[FertNan_filter | AgeNan_filter, :]

,Country_(OrDependency),Population_2023,Yearly_Change(%),Net_Change,Density_(P/Km²),LandArea_(Km²),Migrants_(net),Fert_Rate,Med_Age,Urban_Pop(%),World_Share(%)
233,Holy See,518,1.57 %,8,"1,295",0,0,NaN,NaN,N.A.,0.00 %

In [ ]:
df1=df
HolySee_filter = df1["Country_(OrDependency)"] == "Holy See"
df1.loc[HolySee_filter, "Fert_Rate"] = 1.0
df1.loc[HolySee_filter, "Med_Age"] = 57
df1.loc[HolySee_filter, :]

,Country_(OrDependency),Population_2023,Yearly_Change(%),Net_Change,Density_(P/Km²),LandArea_(Km²),Migrants_(net),Fert_Rate,Med_Age,Urban_Pop(%),World_Share(%)
233,Holy See,518,1.57 %,8,"1,295",0,0,1.0,57.0,N.A.,0.00 %

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country_(OrDependency)  234 non-null    object
 1   Population_2023         234 non-null    object
 2   Yearly_Change(%)        234 non-null    object
 3   Net_Change              234 non-null    int64
 4   Density_(P/Km²)         234 non-null    object
 5   LandArea_(Km²)          234 non-null    int64
 6   Migrants_(net)          234 non-null    int64
 7   Fert_Rate               234 non-null    float64
 8   Med_Age                 234 non-null    float64
 9   Urban_Pop(%)            234 non-null    object
 10  World_Share(%)          234 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 20.2+ KB